create tabla
ID_RESERVACION INTEGER PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INTEGER, ID_TARJETA INTEGER,
CIUDAD_DESTINO VARCHAR(120).
NOMBRE_HOTEK VARCHAR(120), NUMERO_PERSONAS INTEGER,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY(ID_TARJETA) REFERENCES TARJETA1(ID_TARJETA);

SELECT * FROM RESERVACION;
